### ISSUE TITLE
Script is not working for me

### ISSUE THREAD

**Issue by maheshwagh1989** [kmonticolo/Ansible-on-SLES11#3]
Hello,

The repository URL from the script are not working. Do you know whether we can still install Ansible on Suse 11 SP2?

**Comment by kmonticolo** [comment]
I noticed it yesterday, that some repositories were missing, when I was
trying to setup CI on that project.
Please sched some light on the issue:
- Are you using Vagrant ot real environment?
- Could you please attach output and error code? ( echo $? )
- Do you have an access to  SLES repository?
I will be glad to help you.

Regards
Kamil

15.02.2018 9:42 PM "maheshwagh1989" <notifications@github.com> napisał(a):

**Comment by kmonticolo** [comment]
I was also having difficulties to search proper repositories, when I wrote
that script. I will try to search another one.

Kamil

15.02.2018 9:42 PM "maheshwagh1989" <notifications@github.com> napisał(a):

**Comment by kmonticolo** [comment]
@maheshwagh1989 It works again, please test and let me know.
Cheers,
Kamil

**Comment by kmonticolo** [comment]
fixed
